/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    Check: typeof import('./src/components/icons/Check.vue')['default']
    Expand: typeof import('./src/components/icons/Expand.vue')['default']
    Github: typeof import('./src/components/icons/Github.vue')['default']
    IconBtn: typeof import('./src/components/IconBtn.vue')['default']
    IconTextBtn: typeof import('./src/components/IconTextBtn.vue')['default']
    LangPicker: typeof import('./src/components/LangPicker.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    ModePicker: typeof import('./src/components/ModePicker.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    PageLayout: typeof import('./src/layouts/PageLayout.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    Quiz: typeof import('./src/components/icons/Quiz.vue')['default']
    Refresh: typeof import('./src/components/icons/Refresh.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Speaker: typeof import('./src/components/icons/Speaker.vue')['default']
    TargetWordChar: typeof import('./src/components/TargetWordChar.vue')['default']
    X: typeof import('./src/components/icons/X.vue')['default']
  }
}
